os:
  - linux

sudo: false

git:
  depth: 1

matrix:
  include:
    - language: php
      php: 7.1
      before_install: .travis/php/before_install.sh
      install: .travis/php/install.sh
      before_script: .travis/php/before_script.sh
      script: .travis/php/script.sh

    - language: php
      php: 7.2
      before_install: .travis/php/before_install.sh
      install: .travis/php/install.sh
      before_script: .travis/php/before_script.sh
      script: .travis/php/script.sh

    - language: php
      php: nightly
      before_install: .travis/php/before_install.sh
      install: .travis/php/install.sh
      before_script: .travis/php/before_script.sh
      script: .travis/php/script.sh

    - language: python
      python: 2.7
      install: .travis/python/install.sh
      script: .travis/python/script.sh

    - language: python
      python: 3.6
      install: .travis/python/install.sh
      script: .travis/python/script.sh

  allow_failures:
    - php: nightly

  fast_finish: true
