language: php

os:
  - linux

git:
  depth: 1

php:
    - 7.1
    - 7.2
    - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly


sudo: false

before_install: "phpenv config-rm xdebug.ini 2>/dev/null || :"

install:
  - composer install --no-interaction
  - vendor/bin/codecept --version

before_script:
  - vendor/bin/codecept clean --no-interaction
  - vendor/bin/codecept build --no-interaction

script:
  - find src tests %s -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - vendor/bin/phpcs --standard=.php_cs_ruleset.xml --encoding=utf-8 --ignore=tests/**/_bootstrap.php,tests/_support/*Tester.php src tests
  - vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=tests/**/_bootstrap.php,tests/_support/*Tester.php src tests
  - vendor/bin/codecept run --no-interaction
